pipeline changes

diff --git a/.github/workflows/selenium-test.yml b/.github/workflows/selenium-test.yml
--- a/.github/workflows/selenium-test.yml
+++ b/.github/workflows/selenium-test.yml
@@ -1,14 +1,12 @@
 name: Java CI with Maven
 
 on:
-  pull_request:
-    types: [opened, synchronize, reopened, closed]
+  push:
     branches:
-      - poc
+      - "report-on-slack-check"
 
 jobs:
   deploy:
-    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
     runs-on: ubuntu-latest
     environment:
       name: poc
@@ -62,12 +60,49 @@ jobs:
         path: /home/runner/work/github-actions/github-actions/automation-testing/reports/index.html
         if-no-files-found: warn
 
-    - name: Slack Notification
-      uses: rtCamp/action-slack-notify@v2
+    - name: Get Artifact ID
+      id: get-artifact-id
+      run: |
+        ARTIFACT_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[0].id')
+        echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
+
+    - name: Construct artifact URL
+      id: construct-url
+      run: |
+        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${ARTIFACT_ID}"
+        echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV
+
+    - name: Send test report to Slack
       env:
-        SLACK_CHANNEL: notifications
-        SLACK_COLOR: ${{ job.status }} 
-        SLACK_MESSAGE: 'Post Content :rocket:'
-        SLACK_TITLE: Post Title
-        SLACK_USERNAME: chandana Govada
-        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
+        SLACK_CHANNEL: 'test'
+        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
+        ARTIFACT_URL: ${{ env.ARTIFACT_URL }}
+      run: |
+        echo "Sending artifact URL to Slack..."
+
+        # Post a message with the artifact URL
+        message_response=$(curl -s -X POST -H "Authorization: Bearer ${SLACK_TOKEN}" \
+                                  -H "Content-type: application/json" \
+                                  --data "{
+                                    \"channel\": \"${SLACK_CHANNEL}\",
+                                    \"text\": \"Test Report :rocket:\",
+                                    \"attachments\": [
+                                      {
+                                        \"title\": \"Test Report for Job\",
+                                        \"title_link\": \"${ARTIFACT_URL}\",
+                                        \"text\": \"The test report can be viewed from the link above.\"
+                                      }
+                                    ]
+                                  }" \
+                                  https://slack.com/api/chat.postMessage)
+        
+        echo "Message response: $message_response"
+
+        # Check if the message was sent successfully
+        message_ok=$(echo $message_response | jq -r '.ok')
+        if [ "$message_ok" != "true" ]; then
+          echo "Message post failed: $message_response"
+          exit 1
+        fi
+
+        echo "Message posted successfully."
