pipeline changes

diff --git a/.github/workflows/selenium-test.yml b/.github/workflows/selenium-test.yml
--- a/.github/workflows/selenium-test.yml
+++ b/.github/workflows/selenium-test.yml
@@ -62,14 +62,24 @@ jobs:
 
     - name: Get Artifact ID
       id: get-artifact-id
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        ARTIFACT_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[0].id')
+        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+                         -H "Accept: application/vnd.github.v3+json" \
+                         "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")
+        echo "Response: $response"
+        ARTIFACT_ID=$(echo $response | jq -r '.artifacts[0].id')
+        if [ -z "$ARTIFACT_ID" ]; then
+          echo "Artifact ID not found"
+          exit 1
+        fi
         echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
 
     - name: Construct artifact URL
       id: construct-url
       run: |
-        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${ARTIFACT_ID}"
+        ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ env.ARTIFACT_ID }}"
         echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV
 
     - name: Send test report to Slack
